name: Build EXE
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: msbuild de4dot.sln /p:Configuration=Release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: de4dot-vg-compiled
          path: de4dot.cui/bin/Release/
